import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import UserProvider from '../../contexts/user';
import UpperBodyProvider from '../../contexts/fromUpperBody';
import ProfilProvider from '../../contexts/profil';
import ShirtProvider from '../../contexts/fromShirt';
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider>
        <UpperBodyProvider>
          <ShirtProvider>
            <ProfilProvider>
              <body className={inter.className}>{children}</body>
            </ProfilProvider>
          </ShirtProvider>
        </UpperBodyProvider>
      </UserProvider>
    </html>
  )
}
